name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
assignees:
  - lishaduck
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug!
      placeholder: Tell us what you saw!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How did you trigger this bug? Please walk us through it step by step."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        etc.
        ...
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      description: Describe what you think should have happened!
      placeholder: I think...
      value: "That wasn't supposed to happen!"
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: When did this bug happen?
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: What device are you seeing the problem on?
      description: What device (eg. Pixel 4, iPhone 9, IBM PS/2 Note, Apple I)
  - type: dropdown
    id: os
    attributes:
      label: What OSes are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux/GNU
        - ChromeOS
        - iOS
        - Andriod
        - Fuchsia
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Anything thing else to add? Screenshots appreciated.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
