name: 📝 Enhancement Plan
description: File an enhancement plan
type: "enhancement"
body:
  - type: textarea
    id: reason
    attributes:
      label: Why
      description: Why do we need this?
      placeholder: Quick summary of why we need this enhancement and what it will do for us.
      value: A reason goes here!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please remember to break this up into as many sub-issues (of type of "Task") as needed for this enhancement.
